---
vm_types:
- name: web
  cloud_properties:
    instance_type: t2.medium
- name: database
  cloud_properties:
    instance_type: t2.medium
- name: worker
  cloud_properties:
    instance_type: t2.xlarge
    ephemeral_disk:
      size: 200000
      type: standard
- name: compilation
  cloud_properties:
    instance_type: c3.large
    ephemeral_disk:
      size: 200_00
      type: standard

azs:
- name: z1
  cloud_properties:
    availability_zone: (( .cloud_properties.az ))

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.17.0/24
        reserved: [10.0.17.2 - 10.0.17.9]
        static: [10.0.17.31]
        dns: [10.0.0.2]
        gateway: 10.0.17.1
        az: z1
        cloud_properties:
          security_groups:
            - (( .cloud_properties.security_group_name ))
          subnet: (( .cloud_properties.subnet_id ))

disk_types:
- name: database
  disk_size: 10_240
  cloud_properties: {type: gp2}

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  vm_type: compilation
  az: z1

cloud_properties: (( merge ))
