---
name: concourse

director_uuid: (( merge ))

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: web
  stemcell: trusty
  azs: [z1]
  networks: 
  - name: concourse
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: (( atc_credentials.external_url || nil ))
      github_auth: (( atc_credentials.github_auth || nil ))
      basic_auth_username: (( atc_credentials.basic_auth_username ))
      basic_auth_password: (( atc_credentials.basic_auth_password ))
      publicly_viewable: true
      postgresql:
        database: (( atc_credentials.db_name ))
        role:
          name: (( atc_credentials.db_user ))
          password: ((atc_credentials.db_password ))
  - name: tsa
    release: concourse
    properties:
      atc:
          username: (( atc_credentials.basic_auth_username ))
          password: (( atc_credentials.basic_auth_password ))

- name: db
  instances: 1
  vm_type: database
  stemcell: trusty
  persistent_disk_type: database
  azs: [z1]
  networks: [{name: concourse}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      postgresql:
        databases:
        - name: (( atc_credentials.db_name ))
        roles:
        - name: (( atc_credentials.db_user ))
          password: ((atc_credentials.db_password ))

- name: worker
  instances: 1
  vm_type: worker
  stemcell: trusty
  azs: [z1]
  networks: [{name: concourse}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-linux
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        btrfs_store_size_mb: 100000
    
update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

cloud_properties: (( merge ))
atc_credentials: (( merge ))
datadog_properties: (( merge || nil ))
syslog_properties: (( merge || nil ))
